<%@ Page Title="" Language="C#" MasterPageFile="~/Site2.Master" AutoEventWireup="true" CodeBehind="addproduct.aspx.cs" Inherits="ice_cream.addproduct" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <asp:Label ID="Label1" runat="server" ForeColor="Black"></asp:Label>
    <br />
<form runat="server">
<center>
    <asp:Label ID="Label2" runat="server" style="text-align: center" 
    Text="Item Managment" Font-Bold="True" Font-Size="XX-Large" Font-Italic="True" 
        Font-Names="High Tower Text" Font-Underline="True"></asp:Label></center>
<br />

<asp:GridView ID="GridView1" runat="server" 
    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
    AutoGenerateSelectButton="True" CellPadding="3" DataKeyNames="id" 
    DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical" 
    style="text-align: center" 
    
    AutoGenerateColumns="False" Width="1500px" BackColor="White" 
    BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px">
    <AlternatingRowStyle BackColor="#CCCCCC" />
    <Columns>
        <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" 
            ReadOnly="True" SortExpression="id" />
        <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
        <asp:BoundField DataField="price" HeaderText="price" SortExpression="price" />
        <asp:BoundField DataField="image" HeaderText="image" SortExpression="image" />
    </Columns>

    <FooterStyle BackColor="#CCCCCC" />
    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
    <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
    <SortedAscendingCellStyle BackColor="#F1F1F1" />
    <SortedAscendingHeaderStyle BackColor="#808080" />
    <SortedDescendingCellStyle BackColor="#CAC9C9" />
    <SortedDescendingHeaderStyle BackColor="#383838" />
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>" 
    DeleteCommand="DELETE FROM [product] WHERE [id] = @id" 
    InsertCommand="INSERT INTO [product] ([name], [price], [image]) VALUES (@name, @price, @image)" 
    SelectCommand="SELECT * FROM [product]" 
    
    UpdateCommand="UPDATE [product] SET [name] = @name, [price] = @price, [image] = @image WHERE [id] = @id">
    <DeleteParameters>
        <asp:Parameter Name="id" Type="Int32" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="name" Type="String" />
        <asp:Parameter Name="price" Type="String" />
        <asp:Parameter Name="image" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="name" Type="String" />
        <asp:Parameter Name="price" Type="String" />
        <asp:Parameter Name="image" Type="String" />
        <asp:Parameter Name="id" Type="Int32" />
    </UpdateParameters>
</asp:SqlDataSource>
<center>
    <br />
    <br />
    name:<asp:TextBox ID="TextBox1" runat="server" style="text-align: right"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;
price:<asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
&nbsp;&nbsp;&nbsp;&nbsp;
image:<asp:FileUpload ID="FileUpload1" runat="server" /></center>
<br />
<center>

    <asp:Button ID="Button1" runat="server" 
    style="text-align: center" Text="add"  Height="55px" 
                       Width="146px" BackColor="Black" Font-Bold="True" 
                      Font-Italic="True" Font-Size="Larger" ForeColor="White" 
                      BorderColor="White" BorderWidth="5px" 
        onclick="Button1_Click" />
    <br />
    <br />
    <br />
    <br />
</center>
</form>
    
</asp:Content>
